config/routes.rb
Combatgent::Application.routes.draw do

  match "lookbooks" => "products#lookbooks"
  match "my_closet" => "users#closet"
  
  resources :users do
    member do
      get :closet
    end
  end
  
  resources :closet_items
  resources :outfits
  
  namespace :admin do
    resources :fits
    resources :outfits do
      resources :outfit_images
      resources :outfit_products do
        member do
          get :select
          get :remove
        end
        collection do
          get :available
          get :selected
        end
      end
    end
  end
  
  match '/products', :controller=>'products', :action=>'index' 
end

app/views/shared/_add_to_closet.html.erb
<% if current_user %>
  <% if current_user.product_in_closet?(product) %>
    <%= button_to "Remove From Closet", current_user.closet_item(product), :method => 'delete', :class => 'closet_button' %>
  <% else %>
    <%= form_for ClosetItem.new(:product => product) do |f| %>
      <%= f.hidden_field :product_id %>
      <%= f.submit "Save to closet", :class => 'closet_button' %>
    <% end %>
  <% end %>
<% else %>
  <%= button_to "Login to save", login_path, :method => 'get', :class => 'closet_button' %>
<% end %>

app/views/shared/_expanded_footer.html.erb
<section id="expanded_footer">
	<div id="connect">
		<h2>Connect with Combat Gent</h2>
		<p>Stay current with our latest and greatest through a social network of your choosing.</p>
		<%= link_to "Facebook", 'http://www.facebook.com/combatgent' %>&nbsp;&nbsp;|&nbsp;
		<%= link_to "Twitter", 'http://www.twitter.com/combatgent' %>&nbsp;&nbsp;|&nbsp;
		<%= link_to "Tumblr", 'http://blog.combatgent.com' %>
	</div>
	<div id="blog" class="last">
		<h2>Latest Blog</h2>
		<p id="tumbtitle">Musings from our venerable fashion mavens. Click below to see how the sausage is made.</p>		
		<a href="#" id="tumblink">Read It</a>
	</div>
	<div id="returns_exchanges">
		<h2>Returns &amp; Exchanges</h2>
		<p>Didn't fit the way you had hoped? Products damaged by a careless mail person? We'll make things right.</p>
		<%= link_to 'Make a return/exchange', page_path('returns-exchanges') %>
	</div>
	<hr />
</section>

app/views/shared/_head.html.erb
<title><%= title %></title>
<link rel="shortcut icon" href="../images/bowtie-favicon.png">
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<%== meta_data_tags %>
<%= csrf_meta_tag %>
<%= javascript_include_tag 'jquery-1.6.1.min', 'jquery.validate.min.js', 'rails', 'application', :cache => 'jquery-core' %>
<script type="text/javascript" src="https://use.typekit.com/xzv4phj.js"></script>
<script type="text/javascript">try{Typekit.load();}catch(e){}</script>
<%= yield :head %>

app/views/shared/_header_toolbar.html.erb
<div id="toolbar">
  <ul>
    <li class="social facebook"><%= link_to 'Facebook', 'http://www.facebook.com/combatgent' %></li>
    <li class="social twitter"><%= link_to 'Twitter', 'http://twitter.com/combatgent' %></li>
    <li class="social blog"><%= link_to 'Blog', 'http://blog.combatgent.com' %></li>
    <li class="social feedback"><%= link_to 'Feedback', 'mailto:feedback@combatgent.com' %></li>	
    <li class="social service"><span>24/7 Customer Service 1-866-966-5436</span></li>
		<li class="action cart"><%= link_to_cart %></li>
		<% if current_user %>
		<li class="action profile">
			<%= link_to t('my_account'), account_path %>
			<ul>
		  	<li><%= link_to t('my_closet'), my_closet_path %></li>
		  	<li><%= link_to t('logout'), destroy_user_session_path %></li>
			</ul>
		</li>
		<% else %>
		<li>
			<li class="action profile">
				<%= link_to t('log_in'), login_path %>	
				<ul>
		  		<li><%= link_to 'SignUp', '/signup' %></li>
				</ul>
			</li>
		<% end %>
  <ul>
</div>

app/views/shared/_javascript_footer.html.erb
<%= javascript_include_tag 'jquery-ui-1.8.16.custom.min' %>
<%= javascript_include_tag "jquery.easing.1.3" %>
<%= javascript_include_tag "plugins/coda-slider/jquery.coda-slider-2.0" %>
<%= javascript_include_tag "jquery.tools" %>
<%= javascript_include_tag 'combat_gent' %>
<%= javascript_include_tag "modernizr-1.7.min.js" %>
<%= javascript_include_tag "jquery.fancybox-1.3.4.js" %>
<% unless I18n.locale.to_s[0..1] == 'en' %>
  <%= javascript_include_tag ['jquery.validate/localization/messages_', I18n.locale.to_s[0..1], '.js'].join %>
<% end %>

app/views/shared/_join_mailing_list.html.erb
<form action="http://combatgent.us2.list-manage.com/subscribe/post?u=2be61b8047b53ce636e939420&amp;id=d9662ef326" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank">
	<p><strong>Join our mailing list!</strong>&nbsp;&nbsp;Sign up to receive emails with updates and special offers</p> 
	<fieldset>
		<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL" placeholder="your@email.com">
		<input type="submit" value="Subscribe" name="Sign Up" id="mc-embedded-subscribe" class="button">
	</fieldset>
</form>

app/views/shared/_login_bar.html.erb
<% if current_user %>
  <li><%= link_to t('my_account'), account_path %></li>
  <li><%= link_to t('my_closet'), my_closet_path %></li>
  <li><%= link_to t('logout'), destroy_user_session_path %></li>
<% else %>
  <li><%= link_to t('log_in'), login_path %></li>
<% end %>

app/views/shared/_match_to_outfit.html.erb
<% if product.outfit.present? %>
  <%= form_tag outfit_url(product.outfit), :method => :get do %>
    <%= hidden_field_tag :product_id, product.id %>
    <%= submit_tag "Match" %>
  <% end %>
<% end %>

app/views/shared/_nav_bar.html.erb
<% @taxons = @taxon && @taxon.parent ? @taxon.parent.children : Taxon.roots  %> 	
<%= render 'shared/search' %>

app/views/shared/_page_footer.html.erb
<ul>
  <li class="about"><%= link_to 'About', page_path('about') %></li>
  <!-- <li class="faq"><%= link_to 'FAQ', page_path('faq') %></li> -->
  <li class="perfect_fit"><%= link_to 'The Perfect Fit', page_path('the-perfect-fit') %></li>
  <!-- <li class="help"><%= link_to 'Help', page_path('help') %></li> -->
  <li class="returns_exchanges"><%= link_to 'Returns & Exchanges', page_path('returns-exchanges') %></li>
  <li class="terms_conditions"><%= link_to 'Terms & Conditions', page_path('terms-and-conditions') %></li>
  <li class="contact_us"><%= link_to 'Contact Us', page_path('contact') %></li>
	<li class="copyright">&copy; 2012 Combat Gent. All rights reserved.</li>
</ul>

app/views/shared/_product_category_menu.html.erb
<li class="home"><a href="/">Home</a></li>
<li class="lookbooks"><%= link_to 'Lookbooks', lookbooks_path %></li>
<% Taxon.header_navigation.each do |taxon| %>
  <li><%= link_to taxon.name, seo_url(taxon) %></li>
<% end %>
<!-- <li class="about"><%= link_to 'About Us', page_path('about') %></li> -->
<li class="perfect_fit"><%= link_to 'The Perfect Fit', page_path('the-perfect-fit') %></li>
<!-- <li class="sale"><%= link_to 'Sale', '#' %></li> -->

app/views/shared/_product_sorting.html.erb
<!-- 
<%= form_tag '#', :id => "sort" do %> 
  <%= label_tag :sort_order_of, "Sort items in order of:" %>
  <%= select_tag :sort_order_of, options_for_select(["Newest","Oldest","Popularity","Price (high)","Price (low)"], "Newest") %>
  <%= label_tag :only_show, "Only show items available in:" %>
  <%= select_tag :only_show, options_for_select(["My size","My size and larger","My size and smaller","All sizes"], "My size") %>
  <%= label_tag :sale_only, "Sale items only:" %>
	<%= check_box_tag :sale_only, :value => "yes" %> 
<% end %>
-->

app/views/shared/_products.html.erb
<%
  paginated_products = @searcher.products if params.key?(:keywords)
  paginated_products ||= products
%>
<% if products.empty? %>
  <%= t(:no_products_found) %>
<% elsif params.key?(:keywords) %>
  <h3><%= t(:search_results, :keywords => h(params[:keywords])) %></h3>
<% end %>

<% if products.any? %>
<ul class="product-listing">
  <% products.each do |product| %>
    <% if Spree::Config[:show_zero_stock_products] || product.has_stock? %>
      <li id="product_<%= product.id %>" data-hook="products_list_item" class="product">
        <%= link_to  product, :class => 'product_link' do %>
          <%= product_image(product) %>
          <div class='info'>
            <h2><%= product.name %></h2>
            <span class='price selling'><%= product_price(product) %></span>
            <% unless product.categorise_variants_from_option('color').size == 0%>
              <p><%= product.categorise_variants_from_option('color').size %> colors available</p>
            <% end %>
          </div>
        <% end %>
      </li>
    <% end %>
  <% end %>
</ul>
<% end %>

<hr class="space" />

<% if paginated_products.respond_to?(:total_pages)
      params.delete(:search)
      params.delete(:taxon)

%><%= will_paginate(paginated_products,
                    :previous_label => "&#171; #{t('previous')}",
                    :next_label => "#{t('next')} &#187;") %>
<% end %>

app/views/shared/_styles.html.erb
<%= stylesheet_link_tag "generic" %>
<%= stylesheet_link_tag "style.css" %>
<%= stylesheet_link_tag "fancybox.css" %>