config/routes.rb
Combatgent::Application.routes.draw do

  match "lookbooks" => "products#lookbooks"
  match "my_closet" => "users#closet"
  
  resources :users do
    member do
      get :closet
    end
  end
  
  resources :closet_items
  resources :outfits
  
  namespace :admin do
    resources :fits
    resources :outfits do
      resources :outfit_images
      resources :outfit_products do
        member do
          get :select
          get :remove
        end
        collection do
          get :available
          get :selected
        end
      end
    end
  end
  
  match '/products', :controller=>'products', :action=>'index' 
end

app/models/outfit_image.rb
class OutfitImage < Image
  validate :no_attachement_errors
  has_attached_file :attachment,
                    :styles => { :mini => '48x48>', :small => '100x100>', :product => '240x240>', :large => '600x600>' },
                    :storage => :s3,
                    :bucket => 'combatgent',
                    :s3_credentials => "#{RAILS_ROOT}/config/s3.yml",
                    :default_style => :small,
                    :url => "outfits/:id/:style/:basename.:extension",
                    :path => "outfits/:id/:style/:basename.:extension"
end

app/controllers/admin/outfit_images_controller.rb
class Admin::OutfitImagesController < Admin::ResourceController
  before_filter :load_data

  create.before :set_viewable
  update.before :set_viewable
  destroy.before :destroy_before

  def update_positions
    params[:positions].each do |id, index|
      Image.update_all(['position=?', index], ['id=?', id])
    end

    respond_to do |format|
      format.js  { render :text => 'Ok' }
    end
  end

  private
  
    def location_after_save
      admin_outfit_outfit_images_url(@outfit)
    end

    def load_data
      @outfit = Outfit.find(params[:outfit_id])
    end

    def set_viewable
      @outfit_image.viewable = @outfit
    end

    def destroy_before
      @viewable = @outfit_image.viewable
    end

end

app/views/admin/outfit_images/_form.html.erb
<tr>
  <td><%= t("filename") %>:</td>
  <td><%= f.file_field :attachment %></td>
</tr>
<%= hidden_field_tag :outfit_id, @outfit.id %>
<tr>
  <td><%= t("alt_text") %>:</td>
  <td><%= f.text_area :alt %></td>
</tr>

app/views/admin/outfit_images/edit.html.erb
<%= render :partial => 'admin/shared/outfit_tabs', :locals => {:current => "Images"} %>

<%= render "shared/error_messages", :target => @outfit_image %>

<%= form_for(:outfit_image, :url => admin_outfit_outfit_image_url(@outfit), :html => { :method => :put, :multipart => true }) do |f| %>
  <table class="basic-table">
    <tr>
      <td><%= t("thumbnail") %>:</td>
      <td><%= link_to(image_tag(@outfit_image.attachment.url(:mini)), @outfit_image.attachment.url(:product)) %></td>
    </tr>
    <%= render :partial => "form", :locals => { :f => f } %>
  </table>
  <p class="form-buttons">
    <%= button t("update") %>
    <%= t('or') %> <%= link_to t("cancel"), admin_outfit_outfit_images_url(@outfit), :id => "cancel_link" %>
  </p>
<% end %>

app/views/admin/outfit_images/index.html.erb
<%= render :partial => 'admin/shared/outfit_tabs', :locals => {:current => "Images"} %>

<table class="index sortable">
  <tr>
    <th><%= t("thumbnail") %></th>
    <th><%= t("alt_text") %></th>
    <th><%= t("action") %></th>
  </tr>

  <% @outfit.outfit_images.each do |outfit_image| %>
    <tr id="<%= dom_id(outfit_image) %>">
      <td>
        <span class="handle"></span>
        <%= link_to(image_tag(outfit_image.attachment.url(:mini)), outfit_image.attachment.url(:product)) %>
      </td>
      <td><%= outfit_image.alt %></td>
      <td class="actions">
        <%= link_to_with_icon('edit', t("edit"), edit_admin_outfit_outfit_image_url(@outfit, outfit_image), :class => 'edit') %>
        &nbsp;
        <%= link_to_delete outfit_image, {:url => admin_outfit_outfit_image_url(@outfit, outfit_image) }%>
      </td>
    </tr>
  <% end %>
</table>

<div id="images"></div>
<br/>
<p>
    <%= link_to icon('add') + ' ' + t("new_image"), new_admin_outfit_outfit_image_url(@outfit), :id => "new_image_link" %>
</p>

<% content_for :head do %>
  <script type="text/javascript">
    jQuery(document).ready(function(){

      jQuery('#new_image_link').click(function (event) {
        event.preventDefault();
        jQuery(this).hide();
        jQuery.ajax({type: 'GET', url: this.href, data: ({authenticity_token: AUTH_TOKEN}), success: function(r){ jQuery('#images').html(r);} });
      });

    });
  </script>
<% end %>

app/views/admin/outfit_images/new.html.erb
<h4><%= t("new_image") %></h4>
<%= form_for(:outfit_image, :url => { :controller => 'outfit_images', :action => 'create' }, :html => { :multipart => true }) do |form| %>
  <table class="basic-table">
    <%= render :partial => "form", :locals => { :f => form } %>
  </table>
  <p class="form-buttons">
    <%= button t("update") %>
    <%= t('or') %> <%= link_to t("cancel"), "#", :id => "cancel_link" %>
  </p>
<% end %>


<script type="text/javascript">    
  jQuery('#cancel_link').click(function (event) { 
    jQuery('#new_image_link').show();
    jQuery('#images').html('');
  });  
 
</script>