config/routes.rb
Combatgent::Application.routes.draw do

  match "lookbooks" => "products#lookbooks"
  match "my_closet" => "users#closet"
  
  resources :users do
    member do
      get :closet
    end
  end
  
  resources :closet_items
  resources :outfits
  
  namespace :admin do
    resources :fits
    resources :outfits do
      resources :outfit_images
      resources :outfit_products do
        member do
          get :select
          get :remove
        end
        collection do
          get :available
          get :selected
        end
      end
    end
  end
  
  match '/products', :controller=>'products', :action=>'index' 
end

app/models/fit.rb
class Fit < ActiveRecord::Base
  has_many  :products
end

app/controllers/admin/fits_controller.rb
class Admin::FitsController < Admin::ResourceController
  before_filter :load_data, :except => [:index, :new, :create]

  protected
    
    def load_data
      @fit = Fit.find(params[:id])
    end

end

app/views/admin/fits/_form.html.erb
<%= f.field_container :title do %>
  <%= f.label :title, t("title")%><br />
  <%= f.text_field :title, :class => 'fullwidth title' %>
  <%= f.error_message_on :title %>
<% end %>

<%= f.field_container :description do %>
  <%= f.label :description, t("description")%><br />
  <%= f.text_area :description, {:cols => 40, :rows => 2, :class => 'fullwidth'} %>
  <%= f.error_message_on :description %>
<% end %>

app/views/admin/fits/edit.html.erb
<h1><%== t("editing_fit") + " &ldquo;#{@fit.title}&rdquo;" %></h1>

<% form_for @fit, :url => admin_fit_url(@fit) do |f|%>
  <%= render :partial => "form", :locals => { :f => f } %>
  <%= f.submit 'Save' %>
<% end %>

app/views/admin/fits/index.html.erb
<h1><%= t("listing_fits") %></h1>

<%= render "shared/error_messages", :target => @fit %>

<p>
  <%= link_to icon('add') + ' ' + t("new_fit"), new_admin_fit_url %>
</p>

<table class="index">
  <thead>
    <tr>
      <th><%= t("title") %></th>
      <th><%= t("description") %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @fits.each do |fit| %>
      <tr>
        <td><%= link_to fit.title, edit_admin_fit_url(fit) %></td>
        <td><%= fit.description %></td>
        <td>
          <%= link_to_edit fit %>
          <%= link_to_delete fit %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/fits/new.html.erb
<h1><%= t("new_fit") %></h1>

<% form_for @fit, :url => { :controller => 'fits', :action => 'create' } do |f| %>
  <%= render :partial => "form", :locals => { :f => f } %>
  <%= f.submit 'Create' %>
<% end %>