config/routes.rb
Combatgent::Application.routes.draw do

  match "lookbooks" => "products#lookbooks"
  match "my_closet" => "users#closet"
  
  resources :users do
    member do
      get :closet
    end
  end
  
  resources :closet_items
  resources :outfits
  
  namespace :admin do
    resources :fits
    resources :outfits do
      resources :outfit_images
      resources :outfit_products do
        member do
          get :select
          get :remove
        end
        collection do
          get :available
          get :selected
        end
      end
    end
  end
  
  match '/products', :controller=>'products', :action=>'index' 
end

app/models/outfit.rb
class Outfit < ActiveRecord::Base
  has_many  :outfit_products, :dependent => :destroy
  has_many  :products, :through => :outfit_products
  
  has_many :outfit_images, :as => :viewable, :order => :position, :dependent => :destroy
  
  accepts_nested_attributes_for :outfit_products, :allow_destroy => true, :reject_if => lambda { |op| op[:product_id].blank? }
end

app/controllers/admin/outfits_controller.rb
class Admin::OutfitsController < Admin::ResourceController
  before_filter :load_data, :except => [:index, :new, :create]

  protected
    
    def load_data
      @outfit = Outfit.find(params[:id])
    end

end

app/controllers/outfits_controller.rb
class OutfitsController < Spree::BaseController
  respond_to :html
  
  def show
    @product = Product.find(params[:product_id])
    @outfit = Outfit.find(params[:id])
  end

end

app/views/admin/outfits/edit.html.erb
<%= render :partial => 'admin/shared/outfit_tabs', :locals => {:current => "Outfit Description"} %>

<% form_for @outfit, :url => admin_outfit_url(@outfit) do |f|%>
  <%= render :partial => "form", :locals => { :f => f } %>
  <%= f.submit 'Save' %>
<% end %>

app/views/admin/outfits/index.html.erb
<h1><%= t("listing_outfits") %></h1>

<%= render "shared/error_messages", :target => @outfit %>

<p>
  <%= link_to icon('add') + ' ' + t("new_outfit"), new_admin_outfit_url %>
</p>

<table class="index">
  <thead>
    <tr>
      <th><%= t("title") %></th>
      <th><%= t("description") %></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @outfits.each do |outfit| %>
      <tr>
        <td><%= link_to outfit.title, edit_admin_outfit_url(outfit) %></td>
        <td><%= outfit.description %></td>
        <td>
          <% outfit.outfit_images.each do |outfit_image| %>
            <%= image_tag(outfit_image.attachment.url(:mini)) %>
          <% end %>
        </td>
        <td>
          <%= link_to_edit outfit %>
          <%= link_to_delete outfit %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/outfits/new.html.erb
<h1><%= t("new_outfit") %></h1>

<% form_for @outfit, :url => { :controller => 'outfits', :action => 'create' } do |f| %>
  <%= render :partial => "form", :locals => { :f => f } %>
  <%= f.submit 'Create' %>
<% end %>